language: java
install: true
sudo: true
addons:
  apt:
    packages:
    - oracle-java8-installer
    
stages:

- name: build

jobs:
  include:

  - stage: build
    script: "./gradlew --stacktrace build"
